{% set name = "libmaxminddb" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/maxmind/libmaxminddb/releases/download/{{ version }}/libmaxminddb-{{ version }}.tar.gz
  sha256: b2eea79a96fed77ad4d6c39ec34fed83d45fcb75a31c58956813d58dcf30b19f

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('libmaxminddb') }}
  skip: true  # [win]
  script:
    - "./configure --disable-debug \
        --disable-dependency-tracking \
        --disable-silent-rules \
        --prefix=$PREFIX"
    - make
    - make check            # [build_platform == target_platform]
    - make install

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - make

test:
  commands:
    - mmdblookup -f t/maxmind-db/test-data/GeoIP2-City-Test.mmdb -i 175.16.199.0
  source_files:
    - t/maxmind-db/test-data/GeoIP2-City-Test.mmdb

about:
  home: https://maxmind.github.io/libmaxminddb/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "C library for the MaxMind DB file format"
  description: |
    The libmaxminddb library provides a C library for reading MaxMind DB files, including
    the GeoIP2 databases from MaxMind. This is a custom binary format designed to facilitate
    fast lookups of IP addresses while allowing for great flexibility in the type of
    data associated with an address.
  dev_url: https://github.com/maxmind/libmaxminddb

extra:
  recipe-maintainers:
    - dbast
